id: z420

enabled: true

description: Backup to z420

schedule:
  type: daily
  time: "02:00"

jobs:

  - id: Proxima

    enabled: true

    source: /home/brotech/Proxima

    destination: sans1@192.168.1.10:/backups/roberto/Proxima

    retention: 30

  - id: web-projects

    enabled: true

    source: /home/brotech/web-projects

    destination: sans1@192.168.1.10:/backups/roberto/web-projects

    retention: 30

  - id: projects

    enabled: true

    source: /home/brotech/Projects

    destination: sans1@192.168.1.10:/backups/roberto/Projects

    retention: 30
