# ─── Font ───────────────────────────────────────────────────────────────────
font_family      UbuntuMono Nerd Font Mono Regular
bold_font        UbutnuMono Nerd Font Mono Bold
italic_font      UbuntuMono Nerd Font Mono Italic
bold_italic_font UbuntuMono Nerd Font Mono Bold Italic
font_size        12.5

# ─── Cursor ─────────────────────────────────────────────────────────────────
cursor_shape          beam
cursor_blink_interval 0.5
cursor_stop_blinking_after 0

# ─── Window ─────────────────────────────────────────────────────────────────
background_opacity    1
window_padding_width  12
hide_window_decorations yes
enable_audio_bell     no

# ─── Scrollback ─────────────────────────────────────────────────────────────
scrollback_lines      10000
wheel_scroll_multiplier 3.0

# ─── Selection ──────────────────────────────────────────────────────────────
copy_on_select        yes

# ─── Mouse ──────────────────────────────────────────────────────────────────
mouse_hide_wait       0.5

# ─── Shell ──────────────────────────────────────────────────────────────────
shell                 /bin/bash

# ─── Colors (Tokyo Night) ───────────────────────────────────────────────────
foreground            #c0caf5
background            #1a1b26

cursor                #c0caf5
cursor_text_color     #1a1b26

# normal
color0  #15161e
color1  #f7768e
color2  #9ece6a
color3  #e0af68
color4  #7aa2f7
color5  #bb9af7
color6  #7dcfff
color7  #a9b1d6

# bright
color8  #414868
color9  #f7768e
color10 #9ece6a
color11 #e0af68
color12 #7aa2f7
color13 #bb9af7
color14 #7dcfff
color15 #c0caf5
