[general]
bars = 24
framerate = 60
sensitivity = 120

[input]
method = pulse
source = alsa_input.usb-HP__Inc_HyperX_SoloCast-00.analog-stereo

[output]
method = raw
raw_target = /tmp/audiograph/cava_mic_fifo
data_format = ascii
ascii_max_range = 31
